
name: Build Zygisk Spoofer Full
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
    - name: Create build directory
      run: mkdir build
    - name: Configure with CMake
      run: >
        cmake -S . -B build
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
        -DANDROID_ABI=arm64-v8a
        -DANDROID_PLATFORM=android-29
    - name: Build shared library
      run: cmake --build build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: libssaidspoof
        path: build/libssaidspoof.so
